In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [29]:
import pandas as pd

In [30]:
# 데이터 불러오기
df = pd.read_csv('/content/drive/MyDrive/2025_데이터마이닝/WiDS/training.csv')
df_test = pd.read_csv('/content/drive/MyDrive/2025_데이터마이닝/WiDS/test.csv')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12906 entries, 0 to 12905
Data columns (total 83 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   patient_id                             12906 non-null  int64
 1   patient_race                           6521 non-null   object
 2   payer_type                             11103 non-null  object
 3   patient_state                          12855 non-null  object
 4   patient_zip3                           12906 non-null  int64
 5   patient_age                            12906 non-null  int64
 6   patient_gender                         12906 non-null  object
 7   bmi                                    3941 non-null   float64
 8   breast_cancer_diagnosis_code           12906 non-null  object
 9   breast_cancer_diagnosis_desc           12906 non-null  object
 10  metastatic_cancer_diagnosis_code       12906 non-null  object
 11  metastatic_first_novel_treatment       24 non-null     object
 12  metastatic_first_novel_treatment_type  24 non-null     object
 13  Region                                 12854 non-null  object
 14  Division                               12854 non-null  object
 15  population                             12905 non-null  float64
 16  density                                12905 non-null  float64
 17  age_median                             12905 non-null  float64
 18  age_under_10                           12905 non-null  float64
 19  age_10_to_19                           12905 non-null  float64
 20  age_20s                                12905 non-null  float64
 21  age_30s                                12905 non-null  float64
 22  age_40s                                12905 non-null  float64
 23  age_50s                                12905 non-null  float64
 24  age_60s                                12905 non-null  float64
 25  age_70s                                12905 non-null  float64
 26  age_over_80                            12905 non-null  float64
 27  male                                   12905 non-null  float64
 28  female                                 12905 non-null  float64
 29  married                                12905 non-null  float64
 30  divorced                               12905 non-null  float64
 31  never_married                          12905 non-null  float64
 32  widowed                                12905 non-null  float64
 33  family_size                            12902 non-null  float64
 34  family_dual_income                     12902 non-null  float64
 35  income_household_median                12902 non-null  float64
 36  income_household_under_5               12902 non-null  float64
 37  income_household_5_to_10               12902 non-null  float64
 38  income_household_10_to_15              12902 non-null  float64
 39  income_household_15_to_20              12902 non-null  float64
 40  income_household_20_to_25              12902 non-null  float64
 41  income_household_25_to_35              12902 non-null  float64
 42  income_household_35_to_50              12902 non-null  float64
 43  income_household_50_to_75              12902 non-null  float64
 44  income_household_75_to_100             12902 non-null  float64
 45  income_household_100_to_150            12902 non-null  float64
 46  income_household_150_over              12902 non-null  float64
 47  income_household_six_figure            12902 non-null  float64
 48  income_individual_median               12905 non-null  float64
 49  home_ownership                         12902 non-null  float64
 50  housing_units                          12905 non-null  float64
 51  home_value                             12902 non-null  float64
 52  rent_median                            12902 non-null  float64
 53  rent_burden                            12902 non-null  float64
 54  education_less_highschool              12905 non-null  float64
 55  education_highschool                   12905 non-null  float64
 56  education_some_college                 12905 non-null  float64
 57  education_bachelors                    12905 non-null  float64
 58  education_graduate                     12905 non-null  float64
 59  education_college_or_above             12905 non-null  float64
 60  education_stem_degree                  12905 non-null  float64
 61  labor_force_participation              12905 non-null  float64
 62  unemployment_rate                      12905 non-null  float64
 63  self_employed                          12902 non-null  float64
 64  farmer                                 12902 non-null  float64
 65  race_white                             12905 non-null  float64
 66  race_black                             12905 non-null  float64
 67  race_asian                             12905 non-null  float64
 68  race_native                            12905 non-null  float64
 69  race_pacific                           12905 non-null  float64
 70  race_other                             12905 non-null  float64
 71  race_multiple                          12905 non-null  float64
 72  hispanic                               12905 non-null  float64
 73  disabled                               12905 non-null  float64
 74  poverty                                12902 non-null  float64
 75  limited_english                        12902 non-null  float64
 76  commute_time                           12905 non-null  float64
 77  health_uninsured                       12905 non-null  float64
 78  veteran                                12905 non-null  float64
 79  Ozone                                  12877 non-null  float64
 80  PM25                                   12877 non-null  float64
 81  N02                                    12877 non-null  float64
 82  DiagPeriodL90D                         12906 non-null  int64
dtypes: float64(68), int64(4), object(11)
memory usage: 8.2+ MB

### **breast_cancer_diagnosis_code**  (유방암 진단 코드)

In [32]:
# breast_cancer_diagnosis_code 값별 등장 횟수
code_counts = df['breast_cancer_diagnosis_code'].value_counts(dropna=False)

# 비율 계산
code_percent = (code_counts / len(df)) * 100

# 합치기
code_summary = pd.DataFrame({
    'Count': code_counts,
    'Percent': code_percent.round(2)
})

code_summary = code_summary.sort_values(by='Count', ascending=False)

print("breast_cancer_diagnosis_code 분포 요약 (Convert 전):")
display(code_summary)

breast_cancer_diagnosis_code 분포 요약 (Convert 전):

                              Count  Percent
breast_cancer_diagnosis_code
1749                           1982    15.36
C50911                         1797    13.92
C50912                         1712    13.27
C50919                         1467    11.37
C50411                          978     7.58
C50412                          877     6.80
C50811                          491     3.80
C50812                          419     3.25
1744                            389     3.01
1748                            307     2.38
C50212                          293     2.27
C50211                          276     2.14
C50511                          213     1.65
C50112                          209     1.62
C50111                          208     1.61
C50512                          176     1.36
C50312                          159     1.23
C50311                          138     1.07
C50011                          108     0.84
C50012                          105     0.81
1742                             98     0.76
1741                             88     0.68
1745                             71     0.55
C50819                           54     0.42
C50419                           48     0.37
C5091                            37     0.29
1743                             34     0.26
C50612                           29     0.22
C50611                           25     0.19
C50319                           16     0.12
C50019                           13     0.10
1746                             12     0.09
C50219                           11     0.09
C50119                           11     0.09
C5041                             9     0.07
19881                             9     0.07
C5081                             8     0.06
C50519                            8     0.06
C509                              3     0.02
C50619                            3     0.02
C50929                            3     0.02
C5021                             3     0.02
C5011                             2     0.02
C5051                             1     0.01
C50021                            1     0.01
C5031                             1     0.01
C50                               1     0.01
1759                              1     0.01
C5001                             1     0.01
C50421                            1     0.01

In [33]:
# # Convert ICD-9 -> ICD-10
# replace_mapping = {
#     '1749': 'C50919',
#     '1744': 'C50419',
#     '1748': 'C50819',
#     '1742': 'C50219',
#     '1741': 'C50119',
#     '1745': 'C50519',
#     '1743': 'C50319',
#     '1746': 'C50619',
#     '19881': 'C7981',
#     '1759': 'C50929'
# }

# # 매핑 적용
# df['breast_cancer_diagnosis_code'] = df['breast_cancer_diagnosis_code'].replace(replace_mapping)

In [34]:
# breast_cancer_diagnosis_code 값별 등장 횟수
code_counts = df['breast_cancer_diagnosis_code'].value_counts(dropna=False)

# 비율 계산
code_percent = (code_counts / len(df)) * 100

# 합치기
code_summary = pd.DataFrame({
    'Count': code_counts,
    'Percent': code_percent.round(2)
})

code_summary = code_summary.sort_values(by='Count', ascending=False)

print("breast_cancer_diagnosis_code 분포 요약 (Convert 후):")
display(code_summary)

breast_cancer_diagnosis_code 분포 요약 (Convert 후):

                              Count  Percent
breast_cancer_diagnosis_code
1749                           1982    15.36
C50911                         1797    13.92
C50912                         1712    13.27
C50919                         1467    11.37
C50411                          978     7.58
C50412                          877     6.80
C50811                          491     3.80
C50812                          419     3.25
1744                            389     3.01
1748                            307     2.38
C50212                          293     2.27
C50211                          276     2.14
C50511                          213     1.65
C50112                          209     1.62
C50111                          208     1.61
C50512                          176     1.36
C50312                          159     1.23
C50311                          138     1.07
C50011                          108     0.84
C50012                          105     0.81
1742                             98     0.76
1741                             88     0.68
1745                             71     0.55
C50819                           54     0.42
C50419                           48     0.37
C5091                            37     0.29
1743                             34     0.26
C50612                           29     0.22
C50611                           25     0.19
C50319                           16     0.12
C50019                           13     0.10
1746                             12     0.09
C50219                           11     0.09
C50119                           11     0.09
C5041                             9     0.07
19881                             9     0.07
C5081                             8     0.06
C50519                            8     0.06
C509                              3     0.02
C50619                            3     0.02
C50929                            3     0.02
C5021                             3     0.02
C5011                             2     0.02
C5051                             1     0.01
C50021                            1     0.01
C5031                             1     0.01
C50                               1     0.01
1759                              1     0.01
C5001                             1     0.01
C50421                            1     0.01

In [35]:
# 코드별로 target 값 분포(count)
code_target_crosstab = pd.crosstab(df['breast_cancer_diagnosis_code'], df['DiagPeriodL90D'])

# target 1 비율 계산
code_target_crosstab['target_1_rate'] = code_target_crosstab[1] / (code_target_crosstab[0] + code_target_crosstab[1])

# 비율 높은 순으로 정렬
code_target_crosstab = code_target_crosstab.sort_values(by='target_1_rate', ascending=False)

print("🧠 breast_cancer_diagnosis_code별 타겟 분포 + 전이율 요약:")
display(code_target_crosstab)

🧠 breast_cancer_diagnosis_code별 타겟 분포 + 전이율 요약:

DiagPeriodL90D                   0     1  target_1_rate
breast_cancer_diagnosis_code
C5011                            0     2       1.000000
C50021                           0     1       1.000000
C50                              0     1       1.000000
C5051                            0     1       1.000000
C5031                            0     1       1.000000
C509                             0     3       1.000000
C50619                           0     3       1.000000
C5021                            0     3       1.000000
C5081                            1     7       0.875000
C50519                           1     7       0.875000
C50811                          84   407       0.828921
C50012                          19    86       0.819048
C50011                          21    87       0.805556
C50311                          28   110       0.797101
C50412                         178   699       0.797035
C50512                          36   140       0.795455
C50812                          87   332       0.792363
C50419                          10    38       0.791667
C50911                         380  1417       0.788536
C50111                          44   164       0.788462
C50411                         212   766       0.783231
C50919                         322  1145       0.780504
C50312                          35   124       0.779874
C5041                            2     7       0.777778
C50912                         382  1330       0.776869
C50212                          66   227       0.774744
C50511                          48   165       0.774648
C50112                          50   159       0.760766
C50211                          71   205       0.742754
C50819                          14    40       0.740741
C50612                           8    21       0.724138
C50611                           7    18       0.720000
C5091                           11    26       0.702703
C50319                           5    11       0.687500
C50929                           1     2       0.666667
C50219                           4     7       0.636364
C50019                           5     8       0.615385
C50119                           5     6       0.545455
1746                             9     3       0.250000
1743                            28     6       0.176471
1742                            85    13       0.132653
19881                            8     1       0.111111
1748                           275    32       0.104235
1741                            79     9       0.102273
1749                          1801   181       0.091322
1744                           355    34       0.087404
1745                            66     5       0.070423
1759                             1     0       0.000000
C5001                            1     0       0.000000
C50421                           1     0       0.000000

In [36]:
# 19881 코드 가진 사람들 필터링
secondary_breast = df[df['breast_cancer_diagnosis_code'] == '19881']

# metastatic 관련 칼럼들 + 타겟 확인
# metastatic_cancer_diagnosis_code, metastatic_first_novel_treatment, metastatic_first_novel_treatment_type, DiagPeriodL90D
columns_to_check = [
    'breast_cancer_diagnosis_desc',
    'metastatic_cancer_diagnosis_code',
    'metastatic_first_novel_treatment',
    'metastatic_first_novel_treatment_type',
    'DiagPeriodL90D'
]

# 결과 출력
print("🔍 19881 코드 환자들의 metastatic 관련 정보 + 타겟 값 확인:")
display(secondary_breast[columns_to_check])

🔍 19881 코드 환자들의 metastatic 관련 정보 + 타겟 값 확인:

,breast_cancer_diagnosis_desc,metastatic_cancer_diagnosis_code,metastatic_first_novel_treatment,metastatic_first_novel_treatment_type,DiagPeriodL90D
1252,Secondary malignant neoplasm of breast,C7981,NaN,NaN,0
4868,Secondary malignant neoplasm of breast,C7951,NaN,NaN,0
5429,Secondary malignant neoplasm of breast,C7981,NaN,NaN,0
7652,Secondary malignant neoplasm of breast,C779,NaN,NaN,0
9523,Secondary malignant neoplasm of breast,C7981,NaN,NaN,0
10328,Secondary malignant neoplasm of breast,C7981,NaN,NaN,1
10595,Secondary malignant neoplasm of breast,C7981,NaN,NaN,0
12325,Secondary malignant neoplasm of breast,C7951,NaN,NaN,0
12650,Secondary malignant neoplasm of breast,C7981,NaN,NaN,0

In [37]:
import numpy as np

# 1. ICD-9/ICD-10 구분하는 새 컬럼 만들기
df['ICD_version'] = np.where(df['breast_cancer_diagnosis_code'].str.isdigit(), 'ICD-9', 'ICD-10')

# 2. ICD-9 vs ICD-10 그룹별로 타겟별(0,1) 환자 수 세기
icd_target_counts = pd.crosstab(df['ICD_version'], df['DiagPeriodL90D'])

# 3. ICD-9 vs ICD-10 그룹별 전이율(mean) 계산
icd_target_means = df.groupby('ICD_version')['DiagPeriodL90D'].mean()

# 4. 둘 다 보기 좋게 합치기
icd_summary = icd_target_counts.copy()
icd_summary['target_1_rate'] = icd_target_means

# 결과 출력
print("🎯 ICD-9 vs ICD-10 환자들의 타겟(0/1) 분포 + 전이율 비교")
display(icd_summary)

🎯 ICD-9 vs ICD-10 환자들의 타겟(0/1) 분포 + 전이율 비교

DiagPeriodL90D     0     1  target_1_rate
ICD_version
ICD-10          2139  7776       0.784266
ICD-9           2707   284       0.094952

**-> breast_cancer_code가 ICD-9인 행들의 전이율이 매우 낮음**

### **breast_cancer_diagnosis_desc** (유방암 진단 설명)

In [38]:
## 성별(female/male), 방향(right/left), unspecified 여부, 부위(upper/lower/central 등) 일치 여부

# 1. 성별 일치 여부
def check_gender(row):
    desc = str(row['breast_cancer_diagnosis_desc']).lower()
    code = row['breast_cancer_diagnosis_code']

    if 'female' in desc:
        return 'female'
    elif 'male' in desc:
        return 'male'
    else:
        return 'unknown'

# 2. 방향(right/left) 일치 여부
def check_side(row):
    desc = str(row['breast_cancer_diagnosis_desc']).lower()

    if 'right' in desc:
        return 'right'
    elif 'left' in desc:
        return 'left'
    else:
        return 'unknown'

# 3. unspecified 여부 (site 불명확 여부)
def check_unspecified(row):
    desc = str(row['breast_cancer_diagnosis_desc']).lower()
    return 'unspecified' if 'unspecified' in desc else 'specified'

# 4. 부위 키워드 대략 매칭 (optional)
def check_area(row):
    desc = str(row['breast_cancer_diagnosis_desc']).lower()

    if 'upper-outer' in desc:
        return 'upper-outer'
    elif 'upper-inner' in desc:
        return 'upper-inner'
    elif 'lower-outer' in desc:
        return 'lower-outer'
    elif 'lower-inner' in desc:
        return 'lower-inner'
    elif 'central' in desc:
        return 'central'
    elif 'nipple' in desc or 'areola' in desc:
        return 'nipple/areola'
    else:
        return 'other/unknown'

# 이제 적용!
df['desc_gender'] = df.apply(check_gender, axis=1)
df['desc_side'] = df.apply(check_side, axis=1)
df['desc_unspecified'] = df.apply(check_unspecified, axis=1)
df['desc_area'] = df.apply(check_area, axis=1)

# 결과 확인
print("🔍 Generated comparison columns:")
display(df[['breast_cancer_diagnosis_code', 'breast_cancer_diagnosis_desc', 'desc_gender', 'desc_side', 'desc_unspecified', 'desc_area']].head(10))

🔍 Generated comparison columns:

,breast_cancer_diagnosis_code,breast_cancer_diagnosis_desc,desc_gender,desc_side,desc_unspecified,desc_area
0,C50919,Malignant neoplasm of unsp site of unspecified...,female,unknown,unspecified,other/unknown
1,C50411,Malig neoplm of upper-outer quadrant of right ...,female,right,specified,upper-outer
2,C50112,Malignant neoplasm of central portion of left ...,female,left,specified,central
3,C50212,Malig neoplasm of upper-inner quadrant of left...,female,left,specified,upper-inner
4,1749,"Malignant neoplasm of breast (female), unspeci...",female,unknown,unspecified,other/unknown
5,1749,"Malignant neoplasm of breast (female), unspeci...",female,unknown,unspecified,other/unknown
6,C50912,Malignant neoplasm of unspecified site of left...,female,left,unspecified,other/unknown
7,C50512,Malig neoplasm of lower-outer quadrant of left...,female,left,specified,lower-outer
8,1744,Malignant neoplasm of upper-outer quadrant of ...,female,unknown,specified,upper-outer
9,C50912,Malignant neoplasm of unspecified site of left...,female,left,unspecified,other/unknown

In [39]:
df["is_female"] = df.breast_cancer_diagnosis_desc.str.contains("female").astype("int")
df["is_female"].value_counts()

is_female
1    12887
0       19
Name: count, dtype: int64

In [40]:
# is_female == 0인 데이터만 필터링
not_female = df[df['is_female'] == 0]

# 그 안에서 patient_gender 확인
gender_check = not_female['patient_gender'].value_counts()
print("🔍 is_female == 0 인 사람들의 patient_gender 분포:")
display(gender_check)

🔍 is_female == 0 인 사람들의 patient_gender 분포:

patient_gender
F    19
Name: count, dtype: int64

In [41]:
# 코드별로 desc 고유값 개수 세기
code_desc_unique_counts = df.groupby('breast_cancer_diagnosis_code')['breast_cancer_diagnosis_desc'].nunique()

# 고유 desc가 1개 초과하는 코드만 보기 (즉, 코드 하나에 여러 desc가 있는 경우)
inconsistent_desc = code_desc_unique_counts[code_desc_unique_counts > 1]

print("🔍 코드별 desc 고유값 개수 요약:")
display(code_desc_unique_counts)

print("\n🚨 desc가 여러 개인 코드들:")
display(inconsistent_desc)

🔍 코드별 desc 고유값 개수 요약:

breast_cancer_diagnosis_code
1741      1
1742      1
1743      1
1744      1
1745      1
1746      1
1748      1
1749      1
1759      1
19881     1
C50       1
C5001     1
C50011    1
C50012    1
C50019    1
C50021    1
C5011     1
C50111    1
C50112    1
C50119    1
C5021     1
C50211    1
C50212    1
C50219    1
C5031     1
C50311    1
C50312    1
C50319    1
C5041     1
C50411    1
C50412    1
C50419    1
C50421    1
C5051     1
C50511    1
C50512    1
C50519    1
C50611    1
C50612    1
C50619    1
C5081     1
C50811    1
C50812    1
C50819    1
C509      1
C5091     1
C50911    1
C50912    1
C50919    1
C50929    1
Name: breast_cancer_diagnosis_desc, dtype: int64

🚨 desc가 여러 개인 코드들:

Series([], Name: breast_cancer_diagnosis_desc, dtype: int64)

In [42]:
# desc별로 그룹화
desc_groups = df.groupby('breast_cancer_diagnosis_desc')

# 그룹별 몇 명씩 있는지 먼저 확인
desc_counts = desc_groups.size().sort_values(ascending=False)

print("🔍 각 desc 그룹별 환자 수:")
display(desc_counts)

🔍 각 desc 그룹별 환자 수:

breast_cancer_diagnosis_desc
Malignant neoplasm of breast (female), unspecified                  1982
Malignant neoplasm of unsp site of right female breast              1797
Malignant neoplasm of unspecified site of left female breast        1712
Malignant neoplasm of unsp site of unspecified female breast        1467
Malig neoplm of upper-outer quadrant of right female breast          978
Malig neoplasm of upper-outer quadrant of left female breast         877
Malignant neoplasm of ovrlp sites of right female breast             491
Malignant neoplasm of ovrlp sites of left female breast              419
Malignant neoplasm of upper-outer quadrant of female breast          389
Malignant neoplasm of other specified sites of female breast         307
Malig neoplasm of upper-inner quadrant of left female breast         293
Malig neoplm of upper-inner quadrant of right female breast          276
Malig neoplm of lower-outer quadrant of right female breast          213
Malignant neoplasm of central portion of left female breast          209
Malignant neoplasm of central portion of right female breast         208
Malig neoplasm of lower-outer quadrant of left female breast         176
Malig neoplasm of lower-inner quadrant of left female breast         159
Malig neoplm of lower-inner quadrant of right female breast          138
Malignant neoplasm of nipple and areola, right female breast         108
Malignant neoplasm of nipple and areola, left female breast          105
Malignant neoplasm of upper-inner quadrant of female breast           98
Malignant neoplasm of central portion of female breast                88
Malignant neoplasm of lower-outer quadrant of female breast           71
Malignant neoplasm of ovrlp sites of unsp female breast               54
Malig neoplasm of upper-outer quadrant of unsp female breast          48
Malignant neoplasm of breast of unspecified site, female              37
Malignant neoplasm of lower-inner quadrant of female breast           34
Malignant neoplasm of axillary tail of left female breast             29
Malignant neoplasm of axillary tail of right female breast            25
Malig neoplasm of lower-inner quadrant of unsp female breast          16
Malignant neoplasm of nipple and areola, unsp female breast           13
Malignant neoplasm of axillary tail of female breast                  12
Malig neoplasm of upper-inner quadrant of unsp female breast          11
Malignant neoplasm of central portion of unsp female breast           11
Malignant neoplasm of upper-outer quadrant of breast, female           9
Secondary malignant neoplasm of breast                                 9
Malignant neoplasm of overlapping sites of breast, female              8
Malig neoplasm of lower-outer quadrant of unsp female breast           8
Malignant neoplasm of unsp site of unspecified male breast             3
Malignant neoplasm of upper-inner quadrant of breast, female           3
Malignant neoplasm of axillary tail of unsp female breast              3
Malignant neoplasm of breast of unspecified site                       3
Malignant neoplasm of central portion of breast, female                2
Malig neoplasm of upper-outer quadrant of right male breast            1
Malignant neoplasm of breast                                           1
Malignant neoplasm of lower-outer quadrant of breast, female           1
Malignant neoplasm of nipple and areola, right male breast             1
Malignant neoplasm of nipple and areola, female                        1
Malignant neoplasm of lower-inner quadrant of breast, female           1
Malignant neoplasm of other and unspecified sites of male breast       1
dtype: int64

In [43]:
# 1. desc별로 그룹화
desc_groups = df.groupby('breast_cancer_diagnosis_desc')

# 2. 주요 특징 요약하기 (patient_age 사용)
desc_summary = desc_groups.agg({
    'DiagPeriodL90D': ['mean', 'count'],  # 전이율 평균, 환자 수
    'patient_age': 'mean',                # 평균 나이
    'income_individual_median': 'mean',                 # 평균 소득
    'female': 'mean',                  # 여성 비율
    'metastatic_cancer_diagnosis_code': pd.Series.nunique  # 서로 다른 전이 부위 코드 종류 수
})

# 3. 컬럼 이름 깔끔하게 다듬기
desc_summary.columns = ['_'.join(col).strip() for col in desc_summary.columns.values]

# 4. 결과 보기
print("🔍 desc 그룹별 주요 특징 요약 (patient_age 기준):")
display(desc_summary.sort_values('DiagPeriodL90D_count', ascending=False))

🔍 desc 그룹별 주요 특징 요약 (patient_age 기준):

,DiagPeriodL90D_mean,DiagPeriodL90D_count,patient_age_mean,income_individual_median_mean,female_mean,metastatic_cancer_diagnosis_code_nunique
breast_cancer_diagnosis_desc,,,,,,
"Malignant neoplasm of breast (female), unspecified",0.091322,1982,59.739657,36321.459032,49.954915,28
Malignant neoplasm of unsp site of right female breast,0.788536,1797,59.283250,36431.300053,49.867581,30
Malignant neoplasm of unspecified site of left female breast,0.776869,1712,59.904206,36557.047278,49.845837,33
Malignant neoplasm of unsp site of unspecified female breast,0.780504,1467,60.519427,36971.297347,49.959430,35
Malig neoplm of upper-outer quadrant of right female breast,0.783231,978,57.958078,36188.822709,49.883670,25
Malig neoplasm of upper-outer quadrant of left female breast,0.797035,877,58.873432,36792.199556,49.805986,23
Malignant neoplasm of ovrlp sites of right female breast,0.828921,491,59.588595,36259.535568,49.891134,20
Malignant neoplasm of ovrlp sites of left female breast,0.792363,419,58.482100,36232.203268,49.943132,17
Malignant neoplasm of upper-outer quadrant of female breast,0.087404,389,56.863753,35658.349824,49.877145,20
Malignant neoplasm of other specified sites of female breast,0.104235,307,57.368078,36542.346333,50.052374,21
Malig neoplasm of upper-inner quadrant of left female breast,0.774744,293,58.675768,36201.584258,49.872538,18
Malig neoplm of upper-inner quadrant of right female breast,0.742754,276,57.615942,37570.713015,49.924568,17
Malig neoplm of lower-outer quadrant of right female breast,0.774648,213,58.408451,37606.898431,49.913780,16
Malignant neoplasm of central portion of left female breast,0.760766,209,59.708134,36417.033284,49.634231,14
Malignant neoplasm of central portion of right female breast,0.788462,208,57.793269,36810.863579,50.075853,16
Malig neoplasm of lower-outer quadrant of left female breast,0.795455,176,58.176136,35611.109137,50.113870,15
Malig neoplasm of lower-inner quadrant of left female breast,0.779874,159,56.773585,35534.036597,49.916583,12
Malig neoplm of lower-inner quadrant of right female breast,0.797101,138,57.195652,37812.019645,49.947681,15
"Malignant neoplasm of nipple and areola, right female breast",0.805556,108,62.712963,36285.981891,49.845578,14
"Malignant neoplasm of nipple and areola, left female breast",0.819048,105,62.600000,36822.650838,49.870596,13
Malignant neoplasm of upper-inner quadrant of female breast,0.132653,98,56.081633,36150.852658,50.005009,15
Malignant neoplasm of central portion of female breast,0.102273,88,58.750000,35265.376521,49.761458,15
Malignant neoplasm of lower-outer quadrant of female breast,0.070423,71,55.056338,37169.915013,49.799740,14
Malignant neoplasm of ovrlp sites of unsp female breast,0.740741,54,59.962963,42124.687346,50.128058,14
Malig neoplasm of upper-outer quadrant of unsp female breast,0.791667,48,55.979167,37814.900568,50.029866,11
"Malignant neoplasm of breast of unspecified site, female",0.702703,37,61.405405,34121.479838,50.193299,7
Malignant neoplasm of lower-inner quadrant of female breast,0.176471,34,60.911765,34909.423492,49.767254,8
Malignant neoplasm of axillary tail of left female breast,0.724138,29,58.034483,37078.364428,50.017989,6
Malignant neoplasm of axillary tail of right female breast,0.720000,25,59.240000,38883.450802,49.797220,7
Malig neoplasm of lower-inner quadrant of unsp female breast,0.687500,16,61.937500,33223.935147,50.197884,10
"Malignant neoplasm of nipple and areola, unsp female breast",0.615385,13,58.923077,38942.643165,49.112331,7
Malignant neoplasm of axillary tail of female breast,0.250000,12,56.166667,37436.486362,49.869917,7
Malig neoplasm of upper-inner quadrant of unsp female breast,0.636364,11,59.272727,37326.503969,50.189884,5
Malignant neoplasm of central portion of unsp female breast,0.545455,11,63.818182,34882.662716,50.747659,6
"Malignant neoplasm of upper-outer quadrant of breast, female",0.777778,9,58.333333,34349.164329,50.346889,4
Secondary malignant neoplasm of breast,0.111111,9,73.555556,36724.921757,50.151302,3
"Malignant neoplasm of overlapping sites of breast, female",0.875000,8,59.375000,35645.102955,50.164923,4
Malig neoplasm of lower-outer quadrant of unsp female breast,0.875000,8,58.000000,38640.669649,49.560479,4
Malignant neoplasm of unsp site of unspecified male breast,0.666667,3,46.666667,39939.377397,50.037169,2
"Malignant neoplasm of upper-inner quadrant of breast, female",1.000000,3,49.666667,32543.918437,49.797761,1
Malignant neoplasm of axillary tail of unsp female breast,1.000000,3,61.666667,36508.202180,49.346390,1
Malignant neoplasm of breast of unspecified site,1.000000,3,66.666667,43737.426273,51.363608,1
"Malignant neoplasm of central portion of breast, female",1.000000,2,78.000000,34946.063880,50.580805,1
Malig neoplasm of upper-outer quadrant of right male breast,0.000000,1,62.000000,37986.750000,50.716667,1
Malignant neoplasm of breast,1.000000,1,68.000000,27712.360000,52.616000,1
"Malignant neoplasm of lower-outer quadrant of breast, female",1.000000,1,60.000000,36059.864860,51.924324,1
"Malignant neoplasm of nipple and areola, right male breast",1.000000,1,62.000000,26743.571430,49.242857,1
"Malignant neoplasm of nipple and areola, female",0.000000,1,72.000000,28711.037740,52.079630,1
"Malignant neoplasm of lower-inner quadrant of breast, female",1.000000,1,43.000000,39491.789470,52.331579,1
Malignant neoplasm of other and unspecified sites of male breast,0.000000,1,82.000000,33892.166670,51.494444,1

### **metastatic_first_novel_treatment** (전이 후 첫 치료)
+ **metastatic_first_novel_treatment_type** (전이 후 첫 치료 유형 설명)

In [44]:
# 1. metastatic_first_novel_treatment 고유값, 결측치 확인
print("== metastatic_first_novel_treatment 고유값: ==")
print(df['metastatic_first_novel_treatment'].value_counts(dropna=False))

# 2. metastatic_first_novel_treatment_type 고유값, 결측치 확인
print("\n== metastatic_first_novel_treatment_type 고유값: ==")
print(df['metastatic_first_novel_treatment_type'].value_counts(dropna=False))

== metastatic_first_novel_treatment 고유값: ==
metastatic_first_novel_treatment
NaN              12882
PEMBROLIZUMAB       13
OLAPARIB            11
Name: count, dtype: int64

== metastatic_first_novel_treatment_type 고유값: ==
metastatic_first_novel_treatment_type
NaN                12882
Antineoplastics       24
Name: count, dtype: int64

***→ 고유값 개수 동일***

- **PEMBROLIZUMAB** : 면역항암 치료제인 PD-1 억제제로, 암세포가 면역체계를 피하는 것을 막아 면역세포가 암세포를 공격하도록 도움


- **OLAPARIB** : PARP 억제제로서, 암세포를 죽이는 데 사용되는 표적 항암제


- **Antineoplastics** : 항암제

In [45]:
# 1. metastatic_first_novel_treatment 값별 전이율 + 샘플 수
print("metastatic_first_novel_treatment별 DiagPeriodL90D 전이율 + 개수")
treatment_summary = df.groupby('metastatic_first_novel_treatment')['DiagPeriodL90D'].agg(['mean', 'count'])
display(treatment_summary)

# 2. metastatic_first_novel_treatment_type 값별 전이율 + 샘플 수
print("\nmetastatic_first_novel_treatment_type별 DiagPeriodL90D 전이율 + 개수")
treatment_type_summary = df.groupby('metastatic_first_novel_treatment_type')['DiagPeriodL90D'].agg(['mean', 'count'])
display(treatment_type_summary)

metastatic_first_novel_treatment별 DiagPeriodL90D 전이율 + 개수

                                      mean  count
metastatic_first_novel_treatment
OLAPARIB                          0.545455     11
PEMBROLIZUMAB                     0.769231     13

metastatic_first_novel_treatment_type별 DiagPeriodL90D 전이율 + 개수

                                           mean  count
metastatic_first_novel_treatment_type
Antineoplastics                        0.666667     24

In [46]:
# treatment 여부에 따라 patient_age, income_mean, bmi 비교
display(df.groupby('metastatic_first_novel_treatment')[['patient_age', 'income_individual_median', 'bmi']].mean())

                                  patient_age  income_individual_median    bmi
metastatic_first_novel_treatment
OLAPARIB                            44.545455              34788.761859  33.95
PEMBROLIZUMAB                       57.538462              38569.354928  31.93

In [47]:
# treatment_type별로 patient_age, income_mean 비교
display(df.groupby('metastatic_first_novel_treatment_type')[['patient_age', 'income_individual_median']].mean())

                                       patient_age  income_individual_median
metastatic_first_novel_treatment_type
Antineoplastics                          51.583333              36836.583105

In [48]:
# 둘 다 값이 있는 사람만 필터링
non_null_both = df[
    df['metastatic_first_novel_treatment'].notna() &
    df['metastatic_first_novel_treatment_type'].notna()
]

# 원하는 네 컬럼 출력
print(f"🔎 치료 관련 칼럼과 income_individual_median, patient_age 출력 (데이터 수: {len(non_null_both)})")
display(non_null_both[['metastatic_first_novel_treatment', 'metastatic_first_novel_treatment_type', 'income_individual_median', 'patient_age']])

🔎 치료 관련 칼럼과 income_individual_median, patient_age 출력 (데이터 수: 24)

,metastatic_first_novel_treatment,metastatic_first_novel_treatment_type,income_individual_median,patient_age
40,OLAPARIB,Antineoplastics,27208.76190,43
107,OLAPARIB,Antineoplastics,27712.36000,47
249,OLAPARIB,Antineoplastics,35253.08772,42
1386,OLAPARIB,Antineoplastics,37965.45833,59
2025,PEMBROLIZUMAB,Antineoplastics,33411.92683,67
2323,PEMBROLIZUMAB,Antineoplastics,44924.00000,75
2379,PEMBROLIZUMAB,Antineoplastics,28834.55172,68
2647,OLAPARIB,Antineoplastics,38888.60417,34
3515,OLAPARIB,Antineoplastics,32849.60417,32
3925,OLAPARIB,Antineoplastics,28367.83333,38
3989,PEMBROLIZUMAB,Antineoplastics,32377.20455,31
4290,OLAPARIB,Antineoplastics,36059.86486,41
5922,PEMBROLIZUMAB,Antineoplastics,32045.58462,42
7346,PEMBROLIZUMAB,Antineoplastics,33821.80556,43
8550,OLAPARIB,Antineoplastics,33644.06557,47
8801,PEMBROLIZUMAB,Antineoplastics,47321.07692,57
9057,PEMBROLIZUMAB,Antineoplastics,31915.49057,51
10494,PEMBROLIZUMAB,Antineoplastics,42578.20000,84
10559,OLAPARIB,Antineoplastics,21242.01818,47
10982,PEMBROLIZUMAB,Antineoplastics,38381.84615,64
11207,PEMBROLIZUMAB,Antineoplastics,51153.90000,50
12200,PEMBROLIZUMAB,Antineoplastics,50743.86047,54
12495,PEMBROLIZUMAB,Antineoplastics,33892.16667,62
12850,OLAPARIB,Antineoplastics,63484.72222,60

In [49]:
# 1. 둘 다 값이 있는 사람만 필터링
non_null_both = df[
    df['metastatic_first_novel_treatment'].notna() &
    df['metastatic_first_novel_treatment_type'].notna()
]

# 2. 필요한 평균 계산
subset_means = non_null_both[['income_individual_median', 'patient_age']].mean()
overall_means = df[['income_individual_median', 'patient_age']].mean()

# 3. 비교 테이블 만들기
comparison = pd.DataFrame({
    'subset_mean': subset_means,
    'overall_mean': overall_means
})

# 결과 출력
print("🎯 치료 정보가 있는 환자 vs 전체 환자 평균 비교 (소득 & 나이)")
display(comparison)

🎯 치료 정보가 있는 환자 vs 전체 환자 평균 비교 (소득 & 나이)

                           subset_mean  overall_mean
income_individual_median  36836.583105  36520.522622
patient_age                  51.583333     59.183326

In [50]:
# 1. 치료 정보 둘 다 값이 있는 사람
non_null_both = df[
    df['metastatic_first_novel_treatment'].notna() &
    df['metastatic_first_novel_treatment_type'].notna()
]

# 2. 치료 정보 없는 사람
null_both = df[
    df['metastatic_first_novel_treatment'].isna() &
    df['metastatic_first_novel_treatment_type'].isna()
]

# 3. 각각 평균 계산
subset_means = non_null_both[['income_individual_median', 'patient_age']].mean()
null_means = null_both[['income_individual_median', 'patient_age']].mean()

# 4. 비교 테이블 만들기
comparison = pd.DataFrame({
    'treatment_info_present': subset_means,
    'treatment_info_absent': null_means
})

# 결과 출력
print("🎯 치료 정보 '있음' vs '없음' 환자 평균 비교 (소득 & 나이)")
display(comparison)

🎯 치료 정보 '있음' vs '없음' 환자 평균 비교 (소득 & 나이)

                          treatment_info_present  treatment_info_absent
income_individual_median            36836.583105           36519.933735
patient_age                            51.583333              59.197485

**→ 치료 칼럼들 제외한 이유가 있음**

> 값이 있는 데이터가 24개뿐이라서, 혹시 이 사람들이 부유한 사람들인가 ? (치료 받았으니) 싶었는데 !

> 또 그런건 아님 .. 평균 (소득, 나이) 비교해보니 비슷해 ~ .. 의미없나봄

### 추가

In [51]:
df["is_female"] = df.breast_cancer_diagnosis_desc.str.contains("female").astype("int")
df["is_female"].value_counts()

is_female
1    12887
0       19
Name: count, dtype: int64

In [52]:
#  Find Product of Pollutants
df["N02xOzonexPM25"]=df["N02"]*df["Ozone"]*df["PM25"]

In [53]:
# Drop some features
# List of columns to iterate over
columns_to_iterate = [col for col in df.columns if col not in ["patient_zip3", "N02xOzonexPM25"]]

# Iterate over each column
for col in columns_to_iterate:
    # Your code to operate on each column goes here
    df["check"]=df.groupby(["patient_zip3","N02xOzonexPM25"])[col].transform("nunique")
    if df["check"].max()==1:
        print("dropped ",col)
        df=df.drop(col,axis=1)
df=df.drop("check",axis=1)

dropped  patient_gender
dropped  metastatic_first_novel_treatment
dropped  metastatic_first_novel_treatment_type
dropped  population
dropped  density
dropped  age_median
dropped  age_under_10
dropped  age_10_to_19
dropped  age_20s
dropped  age_30s
dropped  age_40s
dropped  age_50s
dropped  age_60s
dropped  age_70s
dropped  age_over_80
dropped  male
dropped  female
dropped  married
dropped  divorced
dropped  never_married
dropped  widowed
dropped  family_size
dropped  family_dual_income
dropped  income_household_median
dropped  income_household_under_5
dropped  income_household_5_to_10
dropped  income_household_10_to_15
dropped  income_household_15_to_20
dropped  income_household_20_to_25
dropped  income_household_25_to_35
dropped  income_household_35_to_50
dropped  income_household_50_to_75
dropped  income_household_75_to_100
dropped  income_household_100_to_150
dropped  income_household_150_over
dropped  income_household_six_figure
dropped  income_individual_median
dropped  home_ownership
dropped  housing_units
dropped  home_value
dropped  rent_median
dropped  rent_burden
dropped  education_less_highschool
dropped  education_highschool
dropped  education_some_college
dropped  education_bachelors
dropped  education_graduate
dropped  education_college_or_above
dropped  education_stem_degree
dropped  labor_force_participation
dropped  unemployment_rate
dropped  self_employed
dropped  farmer
dropped  race_white
dropped  race_black
dropped  race_asian
dropped  race_native
dropped  race_pacific
dropped  race_other
dropped  race_multiple
dropped  hispanic
dropped  disabled
dropped  poverty
dropped  limited_english
dropped  commute_time
dropped  health_uninsured
dropped  veteran
dropped  Ozone
dropped  PM25
dropped  N02

In [54]:
for col in df.columns:
    print(col)

patient_id
patient_race
payer_type
patient_state
patient_zip3
patient_age
bmi
breast_cancer_diagnosis_code
breast_cancer_diagnosis_desc
metastatic_cancer_diagnosis_code
Region
Division
DiagPeriodL90D
ICD_version
desc_gender
desc_side
desc_unspecified
desc_area
is_female
N02xOzonexPM25